export const TESTIMONIALS = [
  {
    quote: "We increased daily revenue by 23% in the first month. The AI picks up on things we never would have noticed — like promoting cold brew on humid afternoons.",
    author: "Sarah Chen",
    role: "Owner, Brew & Bean",
    location: "Portland, OR",
    metric: "+23%",
    metricLabel: "revenue",
    accent: "#e07850",
  },
  {
    quote: "The competitor tracking alone is worth it. We get alerts when nearby cafes change prices, and the AI suggests counter-moves instantly. It's like having a strategist on staff 24/7.",
    author: "Marcus Rodriguez",
    role: "Manager, Sunrise Cafe",
    location: "Austin, TX",
    metric: "12",
    metricLabel: "competitors tracked",
    accent: "#c8a070",
  },
  {
    quote: "I used to spend 2 hours every morning deciding what to promote. Now the AI does it in seconds and it's usually right. My mornings are freed up for what matters.",
    author: "Priya Patel",
    role: "Owner, Chai Corner",
    location: "Chicago, IL",
    metric: "2hrs",
    metricLabel: "saved daily",
    accent: "#e07850",
  },
  {
    quote: "The weather analysis is scarily accurate. It predicted a cold front 3 days out and pre-adjusted our menu. We sold 40% more hot drinks that week.",
    author: "James O'Connor",
    role: "Owner, The Warm Cup",
    location: "Seattle, WA",
    metric: "+40%",
    metricLabel: "hot drink sales",
    accent: "#c8a070",
  },
  {
    quote: "We went from guessing to knowing. Every pricing decision now has data behind it. Our margins improved by 8 points in the first quarter.",
    author: "Aisha Williams",
    role: "Manager, Maven Coffee",
    location: "Denver, CO",
    metric: "+8pts",
    metricLabel: "margin gain",
    accent: "#e07850",
  },
] as const;
